# This workflow is run when user pushes to the repository

name: Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 
        - codebuild-GA-CodeBuild-Test-${{ github.run_id }}-${{ github.run_attempt }}
        - image:custom-linux-aws/codebuild/amazonlinux-x86_64-standard:5.0
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        # - name: install psql
        #   run: |
        #     sudo apt-get update
        #     sudo apt-get install -y postgresql-client
        - name: run psql
          run: |
            psql --version